import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync(new URL('../src/variables.ts', import.meta.url), 'utf8');
const url = 'data:text/javascript;base64,' + Buffer.from(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText).toString('base64');
const { ensureVariables, bindingKey, bindableVariables, bindVariable, setVariable, syncVariables, removeVariable, saveVariable, valueAt, convertUnit, displayUnit, displayValue, unitChoices, knownUnit } = await import(url);
const modelSource = readFileSync(new URL('../src/model.ts', import.meta.url), 'utf8');
const modelUrl = 'data:text/javascript;base64,' + Buffer.from(ts.transpileModule(modelSource, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText).toString('base64');
const { initial } = await import(modelUrl);
const starting = ensureVariables(initial);
const startingSymbol = (id, key) => starting.variables.find(v => v.id === starting.bindings[bindingKey(id, key)]).symbol;
assert.equal(startingSymbol('1', 'x'), 'xпов');
assert.equal(startingSymbol('2', 'x'), 'x1');
assert.equal(startingSymbol('3', 'vector.magnitude'), 'aуск1');
assert.deepEqual(ensureVariables(JSON.parse(JSON.stringify(starting))), starting);
assert.equal(convertUnit(10, 'м/с', 'км/ч'), 36);
assert.ok(Math.abs(convertUnit(Math.PI, 'рад', '°') - 180) < 1e-10);
assert.deepEqual(unitChoices('Гц'), ['мкГц', 'мГц', 'Гц', 'кГц', 'МГц', 'ГГц']);
assert.equal(knownUnit('ТГц'), false);
assert.equal(knownUnit('ГН'), false);
assert.equal(knownUnit('Па'), false);
assert.equal(knownUnit('ГПа'), false);
assert.equal(knownUnit('Вт'), false);
assert.equal(convertUnit(1000, 'мГц', 'Гц'), 1);
assert.equal(convertUnit(1, 'МГц', 'Гц'), 1e6);
assert.equal(convertUnit(1, 'ГГц', 'МГц'), 1000);
assert.equal(convertUnit(1, 'см²', 'м²'), 1e-4);
assert.ok(Math.abs(convertUnit(1, 'см³', 'м³') - 1e-6) < 1e-15);
assert.ok(Math.abs(convertUnit(1, 'мг', 'кг') - 1e-6) < 1e-15);
assert.equal(knownUnit('мккг'), false);
assert.equal(displayUnit({ unit: 'рад', value: Math.PI }), '°');
assert.equal(displayValue({ unit: 'рад', value: Math.PI }), 180);
assert.equal(displayUnit({ unit: 'рад/с', value: Math.PI }), '°/с');
assert.equal(displayUnit({ unit: 'рад/с²', value: Math.PI }), '°/с²');
assert.equal(unitChoices('рад')[0], '°');
assert.equal(displayUnit({ unit: 'рад', displayUnit: 'рад', value: Math.PI }), 'рад');
assert.equal(knownUnit('кг/Н'), true);
assert.equal(knownUnit('случайная единица'), false);
const body = (id, mass) => ({ id, index: Number(id), kind: 'rect', x: 0, y: 0, w: 1, h: 1, angle: 0, fixed: false, ends: [null, null], mass, mu: .3, restitution: 0, vx: 0, vy: 0, omega: 0 });
let s = ensureVariables({ version: 2, items: [body('1', 2), body('2', 4)] });
const mass1 = s.bindings[bindingKey('1', 'mass')];
assert.equal(s.variables.find(v => v.id === mass1).visible, true);
const friction = s.bindings[bindingKey('1', 'mu')];
assert.equal(s.variables.find(v => v.id === friction).visible, false);
s = setVariable(s, friction, .6);
assert.equal(s.variables.find(v => v.id === friction).visible, true);
s = { ...s, variables: s.variables.map(v => v.id === friction ? { ...v, visible: false, visibilityLocked: true } : v) };
s = setVariable(s, friction, .9);
assert.equal(s.variables.find(v => v.id === friction).visible, false);
s = ensureVariables({ ...s, items: [...s.items, { id: '3', index: 1, kind: 'acceleration', vector: { x: 0, y: 9.81 }, scope: 'all', targets: [] }] });
const gravity = key => s.variables.find(v => v.id === s.bindings[bindingKey('3', key)]);
assert.equal(gravity('vector.magnitude').visible, true);
assert.equal(gravity('vector.angle').visible, false);
assert.equal(gravity('vector.x').visible, false);
assert.equal(gravity('vector.magnitude').symbol, 'aуск1');
assert.equal(gravity('vector.x').symbol, 'axуск1');
assert.equal(gravity('vector.y').symbol, 'ayуск1');
assert.equal(gravity('vector.angle').value, 270);
s = setVariable(s, gravity('vector.angle').id, 90);
assert.ok(Math.abs(s.items[2].vector.y + 9.81) < 1e-10);
assert.equal(gravity('vector.angle').visible, false);
assert.equal(gravity('vector.y').visible, false);
s = setVariable(s, gravity('vector.magnitude').id, 0);
s = setVariable(s, gravity('vector.angle').id, 180);
s = setVariable(s, gravity('vector.magnitude').id, 2);
assert.ok(Math.abs(s.items[2].vector.x + 2) < 1e-10);
assert.ok(Math.abs(s.items[2].vector.y) < 1e-10);
assert.equal(s.variables.find(v => v.id === s.bindings[bindingKey('1', 'x')]).symbol, 'x1');
assert.equal(s.variables.find(v => v.id === s.bindings[bindingKey('2', 'x')]).symbol, 'x2');
s = ensureVariables({ ...s, items: s.items.map(o => o.id === '3' ? { ...o, index: 12 } : o) });
assert.equal(s.variables.find(v => v.id === s.bindings[bindingKey('3', 'vector.x')]).symbol, 'axуск12');
const surface = { ...body('surface', 0), kind: 'surface', index: 1, w: 4, h: .15, fixed: true };
const placed = ensureVariables({ version: 2, items: [surface, { ...body('rect', 1), index: 1 }] });
assert.equal(placed.variables.find(v => v.id === placed.bindings[bindingKey('surface', 'x')]).visible, false);
assert.equal(placed.variables.find(v => v.id === placed.bindings[bindingKey('surface', 'x')]).symbol, 'xпов');
assert.equal(placed.variables.find(v => v.id === placed.bindings[bindingKey('rect', 'w')]).symbol, 'w1');
const oldSurface = { ...placed, variables: placed.variables.map(v => v.id === placed.bindings[bindingKey('surface', 'x')] ? { ...v, symbol: 'x1', auto: true } : v) };
assert.equal(ensureVariables(oldSurface).variables.find(v => v.id === placed.bindings[bindingKey('surface', 'x')]).symbol, 'xпов');
const manualSurface = { ...oldSurface, variables: oldSurface.variables.map(v => v.id === placed.bindings[bindingKey('surface', 'x')] ? { ...v, symbol: 'xруч', auto: false } : v) };
assert.equal(ensureVariables(manualSurface).variables.find(v => v.id === placed.bindings[bindingKey('surface', 'x')]).symbol, 'xруч');
const connector = (id, kind) => ({ id, index: 1, kind, x: 0, y: 0, w: 1, h: 1, angle: 0, fixed: false, ends: [null, null], length: 1, stiffness: 1, damping: 0, bindings: [] });
const categorized = ensureVariables({ version: 2, items: [
  { ...body('base', 1), index: 1 }, surface,
  { ...body('lever', 1), kind: 'rod', index: 1 },
  { ...body('wheel', 1), kind: 'pulley', index: 1 },
  connector('hinge', 'bearing'), connector('spring', 'spring'), connector('thread', 'rope'),
  ...['force', 'velocity', 'acceleration'].map(kind => ({ id: kind, index: 1, kind, vector: { x: 1, y: 0 }, scope: 'all', targets: [] })),
] });
const symbol = (scene, id, key) => scene.variables.find(v => v.id === scene.bindings[bindingKey(id, key)]).symbol;
for (const [id, expected] of [['base', 'x1'], ['surface', 'xпов'], ['lever', 'xр1'], ['wheel', 'xбл1'], ['hinge', 'xпод1'], ['spring', 'xпр1'], ['thread', 'xн1']])
  assert.equal(symbol(categorized, id, 'x'), expected);
for (const [id, expected] of [['force', 'Fсил1'], ['velocity', 'vскор1'], ['acceleration', 'aуск1']])
  assert.equal(symbol(categorized, id, 'vector.magnitude'), expected);
const leverX = categorized.bindings[bindingKey('lever', 'x')], baseX = categorized.bindings[bindingKey('base', 'x')];
const previousNames = { ...categorized, variables: categorized.variables.map(v => v.id === leverX ? { ...v, symbol: 'x2' } : v.id === baseX ? { ...v, symbol: 'xруч', auto: false } : v) };
const renamed = ensureVariables(JSON.parse(JSON.stringify(previousNames)));
assert.equal(symbol(renamed, 'lever', 'x'), 'xр1');
assert.equal(symbol(renamed, 'base', 'x'), 'xруч');
assert.equal(renamed.bindings[bindingKey('lever', 'x')], leverX);
assert.equal(renamed.items.find(o => o.id === 'lever').index, 1);
const collision = ensureVariables({ ...categorized, variables: [...categorized.variables.filter(v => v.id !== leverX), { id: 'v999', symbol: 'xр1', value: 0, unit: 'м', visible: true, auto: false }], bindings: Object.fromEntries(Object.entries(categorized.bindings).filter(([, id]) => id !== leverX)) });
assert.equal(symbol(collision, 'lever', 'x'), 'xр1′');
const x1 = placed.bindings[bindingKey('surface', 'x')], x2 = placed.bindings[bindingKey('rect', 'x')];
assert.deepEqual(bindableVariables(placed, 'rect', 'x').map(v => v.id), [x2]);
assert.throws(() => bindVariable(placed, 'rect', 'x', x1));
const shown = { ...placed, variables: placed.variables.map(v => v.id === x1 ? { ...v, visible: true, visibilityLocked: true } : v) };
assert.ok(bindableVariables(shown, 'rect', 'x').some(v => v.id === x1));
assert.ok(!bindableVariables(shown, 'rect', 'w').some(v => v.id === x1));
assert.throws(() => bindVariable(shown, 'rect', 'w', x1));
let changedGeometry = syncVariables(placed, { ...placed, items: placed.items.map(o => o.id === 'rect' ? { ...o, x: 3, w: 2, angle: Math.PI / 4 } : o) });
for (const key of ['x', 'w', 'angle']) assert.equal(changedGeometry.variables.find(v => v.id === changedGeometry.bindings[bindingKey('rect', key)]).visible, false);
let motion = ensureVariables({ version: 2, items: [body('1', 1)] });
motion = setVariable(motion, motion.bindings[bindingKey('1', 'velocity.angle')], 90);
motion = setVariable(motion, motion.bindings[bindingKey('1', 'velocity.magnitude')], 3);
assert.equal(motion.items[0].vx, 0);
assert.equal(motion.items[0].vy, -3);
motion = { ...motion, variables: motion.variables.map(v => v.id === motion.bindings[bindingKey('1', 'velocity.magnitude')] ? { ...v, displayUnit: 'км/ч' } : v) };
assert.ok(Math.abs(displayValue(motion.variables.find(v => v.id === motion.bindings[bindingKey('1', 'velocity.magnitude')])) - 10.8) < 1e-10);
motion = saveVariable(motion, { symbol: 'speed', value: 36, unit: 'км/ч' });
const speed = motion.variables.find(v => v.symbol === 'speed');
motion = bindVariable(motion, '1', 'vx', speed.id);
assert.equal(motion.items[0].vx, 10);
motion = syncVariables(motion, { ...motion, items: motion.items.map(o => ({ ...o, vx: 20 })) });
assert.ok(Math.abs(motion.variables.find(v => v.id === speed.id).value - 72) < 1e-10);
motion = saveVariable(motion, { symbol: 'direction', value: Math.PI / 2, unit: 'рад' });
const radians = motion.variables.find(v => v.symbol === 'direction');
assert.equal(displayUnit(radians), 'рад');
motion = ensureVariables({ ...motion, items: [...motion.items, { id: 'effect', index: 1, kind: 'force', vector: { x: 1, y: 0 }, scope: 'all', targets: [] }] });
motion = bindVariable(motion, 'effect', 'vector.angle', radians.id);
assert.ok(Math.abs(motion.items[1].vector.y + 1) < 1e-10);
assert.throws(() => saveVariable(motion, { symbol: 'badUnit', value: 1, unit: 'foo' }));
motion = saveVariable(motion, { symbol: 'inverseForce', value: 1, unit: 'кг/Н' });
assert.equal(motion.variables.find(v => v.symbol === 'inverseForce').unit, 'кг/Н');
s = saveVariable(s, { symbol: 'Q_опыт', value: 2, unit: 'Н' });
const free = s.variables.find(v => v.symbol === 'Q_опыт');
assert.equal(free.visible, true);
assert.equal(free.unit, 'Н');
s = saveVariable(s, { id: free.id, symbol: 'Qэксп', value: 3, unit: 'Н' });
assert.equal(s.variables.find(v => v.id === free.id).value, 3);
assert.throws(() => saveVariable(s, { symbol: 'Qэксп', value: 0, unit: 'Н' }));
s = bindVariable(s, '2', 'mass', mass1);
assert.equal(s.items[1].mass, 2);
s = setVariable(s, mass1, 6);
assert.deepEqual(s.items.filter(o => o.kind === 'rect').map(o => o.mass), [6, 6]);
const next = { ...s, items: s.items.map((o, i) => i ? o : { ...o, mass: 8 }) };
s = syncVariables(s, next);
assert.deepEqual(s.items.filter(o => o.kind === 'rect').map(o => o.mass), [8, 8]);
s = removeVariable(s, mass1);
assert.notEqual(s.bindings[bindingKey('1', 'mass')], s.bindings[bindingKey('2', 'mass')]);
assert.deepEqual(s.items.filter(o => o.kind === 'rect').map(o => o.mass), [8, 8]);
assert.equal(valueAt([{ x: 0, y: 0 }, { x: 1, y: 1 }], .5), .5);
assert.equal(valueAt([{ x: 0, y: 0 }, { x: 1, y: 1, break: true }], .5), 0);
console.log('PASS variables: defaults, custom creation, shared binding, propagation, deletion and graph interpolation');
